[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.build]
cmds = ["python -m venv venv", ". venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
